name: Heimdall binary builder
run-name: Heimdall binary builder
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Heimdall Version'
        required: true
permissions:
  contents: write

env:
  HEIMADALL_VERSION: ${{ github.event.inputs.version }}

jobs:
  build-heimdall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "maticnetwork/heimdall"
          ref: "${{ env.HEIMADALL_VERSION }}"
      - run: "make install"
      - run: tar -czvf heimdall-${{ env.HEIMADALL_VERSION }}.tgz -C /home/runner/go/bin/ heimdalld heimdallcli
      - uses: actions/upload-artifact@v3
        with:
          name: "heimdall-${{ env.HEIMADALL_VERSION }}.tgz"
          path: "heimdall-${{ env.HEIMADALL_VERSION }}.tgz"
  release:
    runs-on: ubuntu-latest
    needs: [build-heimdall]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "heimdall-${{ env.HEIMADALL_VERSION }}.tgz"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            heimdall-${{ env.HEIMADALL_VERSION }}.tgz
          tag_name: "heimdall-${{ env.HEIMADALL_VERSION }}"