name: Polygon FL binary builder
run-name: Polygon FL binary builder
on: [push]
permissions:
  contents: write

env:
  BOR_VERSION: v1.1.0

jobs:
  build-bor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "maticnetwork/bor"
          ref: "${{ env.BOR_VERSION }}"
      - uses: actions/checkout@v4
        with:
          repository: "FastLane-Labs/sentry-patch"
          ref: "main"
          path: "sentry-patch"
      - run: "git apply sentry-patch/announce_only.patch"
      - run: "make bor"
      - run: "go/bin/bor version"
      # - run: tar -czvf bor-${{ env.BOR_VERSION }}.tgz -C go/bin/ bor
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: "bor-${{ env.BOR_VERSION }}.tgz"
      #     path: "bor-${{ env.BOR_VERSION }}.tgz"