name: Polygon FL binary builder
run-name: Polygon FL binary builder
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bor Version'
        required: true
permissions:
  contents: write

env:
  BOR_VERSION: ${{ github.event.inputs.version }}

jobs:
  build-bor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "maticnetwork/bor"
          ref: "${{ env.BOR_VERSION }}"
      - uses: actions/checkout@v4
        with:
          repository: "FastLane-Labs/sentry-patch"
          ref: "main"
          path: "sentry-patch"
      - run: "make bor"
      - run: "cp /home/runner/go/bin/bor /home/runner/go/bin/bor-nopatch"
      - run: "git apply sentry-patch/announce_only.patch"
      - run: "make bor"
      - run: "cp /home/runner/go/bin/bor /home/runner/go/bin/bor-patch"
      - run: tar -czvf bor-${{ env.BOR_VERSION }}.tgz -C /home/runner/go/bin/ bor-nopatch bor-patch
      - uses: actions/upload-artifact@v3
        with:
          name: "bor-${{ env.BOR_VERSION }}.tgz"
          path: "bor-${{ env.BOR_VERSION }}.tgz"
  release:
    runs-on: ubuntu-latest
    needs: [build-bor]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "bor-${{ env.BOR_VERSION }}.tgz"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bor-${{ env.BOR_VERSION }}.tgz
          tag_name: "bor-${{ env.BOR_VERSION }}"